---
site_name: "vega-scverse"
site_url: https://melonora.github.io/vega-scverse
site_author: Wouter-Michiel Vierdag
site_description: >-
  Documentation for the vega-scverse project.

repo_name: melonora/vega-scverse
repo_url: https://github.com/melonora/vega-scverse

copyright: | 
  &copy; 2025 <a href="https://github.com/scverse" target="_blank" rel="noopener">scverse®</a>

theme:
  name: material
  language: en
  features:
    - header.autohide
    - announce
    - announce.dismiss
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    # Palette toggle shown in light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle shown in dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: assets/vega-scverse-logo.png
  favicon: assets/vega-scverse-logo.png

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/square-github
      link: https://github.com/scverse
    - icon: fontawesome/brands/discourse
      link: https://discourse.scverse.org/
    - icon: fontawesome/brands/square-bluesky
      link: https://bsky.app/profile/scverse.bsky.social
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/scverse
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/scverse_team
  announce:
    type: info
    text: "⚠️ This library and its documentation is still under construction!"

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 10.9.0
nav:
  - Home: home.md
  - Index: index.md
  - About: about.md

markdown_extensions:
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - ./tablesort.js

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
