---
name: Auto-deployment of vega_scverse Documentation
on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write  # to let mkdocs write the new docs
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.49.0
          frozen: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Install doc env
        run: pixi install -e doc

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          pixi run -e doc gen_doc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          pixi run -e doc deploy
