name: Preview vega_spatialdata documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.49.0
          frozen: true

      - name: Build documentation
        run: |
          mkdir -p site
          touch site/.nojekyll
          pixi run -e doc gen_doc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          pixi run -e doc mkdocs build -d site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/
          preview-branch: gh-pages
