---
name: Build and test vega_spatialdata

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-24.04, macos-13]
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.49.0
          frozen: true
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Run tests
        run: pixi run -e test test
